version: '3'

volumes:
  vol-emqx-data:
    name: printera-emqx-data
  vol-emqx-etc:
    name: printera-emqx-etc
  vol-emqx-log:
    name: printera-emqx-log

services:
  emqx1:
    image: emqx:5.3.0
    container_name: emqx1
    environment:
      - 'EMQX_NODE_NAME=emqx@node1.emqx.io'
      - 'EMQX_CLUSTER__DISCOVERY_STRATEGY=static'
      - 'EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]'
    healthcheck:
      test: ['CMD', '/opt/emqx/bin/emqx', 'ctl', 'status']
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
          - node1.emqx.io
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - $PWD/etc:/opt/emqx/etc
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

  emqx2:
    image: emqx:5.3.0
    container_name: emqx2
    environment:
      - 'EMQX_NODE_NAME=emqx@node2.emqx.io'
      - 'EMQX_CLUSTER__DISCOVERY_STRATEGY=static'
      - 'EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]'
    healthcheck:
      test: ['CMD', '/opt/emqx/bin/emqx', 'ctl', 'status']
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
          - node2.emqx.io
    volumes:
      - $PWD/etc:/opt/emqx/etc
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

networks:
  emqx-bridge:
    driver: bridge
